bpm:
  in: query
  name: bpm
  description: Return tracks with a specified bpm[from], bpm[to]
  required: false
  style: deepObject
  schema:
    type: object
    properties:
      from:
        type: integer
        description: Return tracks with at least this bpm value
        example: 123
      to:
        type: integer
        description: Return tracks with at most this bpm value
        example: 456
client_id:
  in: query
  name: client_id
  required: true
  schema:
    type: string
  description: The client id belonging to your application
  example: some client
created_at:
  in: query
  name: created_at
  description: (yyyy-mm-dd hh:mm:ss) return tracks created within the specified dates
  required: false
  style: deepObject
  schema:
    type: object
    properties:
      from:
        type: string
        description: (yyyy-mm-dd hh:mm:ss) return tracks created at this date or later
        example: 2020-12-24 00:00:00
      to:
        type: string
        description: (yyyy-mm-dd hh:mm:ss) return tracks created at this date or earlier
        example: 2020-12-26 00:00:00
duration:
  in: query
  name: duration
  description: Return tracks within a specified duration range
  required: false
  style: deepObject
  schema:
    type: object
    properties:
      from:
        type: integer
        description: Return tracks with at least this duration value
        example: 123456
      to:
        type: integer
        description: Return tracks with at most this duration value
        example: 456789
genres:
  in: query
  name: genres
  required: false
  schema:
    type: string
  description: A comma separated list of genres
  example: Pop,House
ids:
  in: query
  name: ids
  required: false
  schema:
    type: string
  description: A comma separated list of track ids to filter on
  example: 1,2,3
limit:
  in: query
  name: limit
  required: false
  schema:
    type: integer
    minimum: 1
    maximum: 200
    default: 50
  description: Number of results to return in the collection.
  example: 2
offset:
  deprecated: true
  in: query
  name: offset
  required: false
  schema:
    type: integer
    default: 0
  description: Offset of first result. Deprecated, use `linked_partitioning` instead.
  example: 0
q:
  in: query
  name: q
  required: true
  schema:
    type: string
  description: search
  example: hello
redirect_uri:
  in: query
  name: redirect_uri
  required: true
  schema:
    type: string
  description: The redirect uri you have configured for your application
  example: https://soundcloud.com
response_type:
  in: query
  name: response_type
  required: true
  schema:
    type: string
    enum:
      - code
  description: Support only the Authorization Code Flow
  example: code
scope:
  in: query
  name: scope
  required: true
  schema:
    type: string
  description: Scope. Leave blank by default
  example: default
state:
  in: query
  name: state
  required: false
  schema:
    type: string
  description: Any value included here will be appended to the redirect URI. Use this for CSRF protection.
  example: encrypted_session_info
tags:
  in: query
  name: tags
  required: false
  schema:
    type: string
  description: A comma separated list of tags
  example: test
url:
  in: query
  name: url
  required: true
  schema:
    type: string
  description: SoundCloud URL
  example: https://soundcloud.com/user-434241656
linked_partitioning:
  in: query
  name: linked_partitioning
  required: false
  schema:
    type: boolean
  description: Returns paginated collection of items (recommended, returning a list without pagination is deprecated and should not be used)
  example: true
secret_token:
  in: query
  name: secret_token
  required: false
  schema:
    type: string
  description: A secret token to fetch private playlists/tracks
access:
  in: query
  name: access
  schema:
    type: array
    items:
      type: string
      enum:
        - playable
        - preview
        - blocked
    default: playable,preview
  description: >
    Filters content by level of access the user (logged in or anonymous) has to the track.
    The result list will include only tracks with the specified access. Include all options if you'd
    like to see all possible tracks. See `Track#access` schema for more details.
  style: form
  explode: false
show_tracks:
  in: query
  name: show_tracks
  required: false
  schema:
    type: boolean
  description: A boolean flag to request a playlist with or without tracks. Default is `true`.
  example: true
# path #
comment_id:
  in: path
  name: comment_id
  required: true
  schema:
    type: integer
  description: SoundCloud comment id
  example: 123456
follower_id:
  in: path
  name: follower_id
  required: true
  schema:
    type: integer
  description: SoundCloud User id to denote a Follower
  example: 743372812
following_id:
  in: path
  name: following_id
  required: true
  schema:
    type: integer
  description: SoundCloud User id to denote a Following of a user
  example: 25219981
playlist_id:
  in: path
  name: playlist_id
  required: true
  schema:
    type: integer
  description: SoundCloud playlist id
  example: 1212781357
fake_playlist_id:
  in: path
  name: playlist_id
  required: true
  schema:
    type: integer
  description: SoundCloud playlist id
  example: 10
repost_playlist_id:
  in: path
  name: playlist_id
  required: true
  schema:
    type: integer
  description: SoundCloud playlist id
  example: 1205584273
tag:
  in: path
  name: tag
  required: true
  schema:
    type: string
  description: tag
  example: some tag
track_id:
  in: path
  name: track_id
  required: true
  schema:
    type: integer
  description: SoundCloud Track id
  example: 308946187
test_track_id:
  in: path
  name: track_id
  required: true
  schema:
    type: integer
  description: SoundCloud Track id
  example: 1015448728
user_id:
  in: path
  name: user_id
  required: true
  schema:
    type: integer
  description: SoundCloud User id
  example: 948745750
user_id_to_follow:
  in: path
  name: user_id
  required: true
  schema:
    type: integer
  description: SoundCloud User id
  example: 743372812
