# Comment to be posted to on PRs from first time contributors in your repository
newPRComment: >
  Thanks for opening this pull request!
  We aim to review the PR's as soon as possible, but please give the team at least 2 working days to review your PR. If your PR is urgent, please ping us in #integrations.
  You can learn more about BFFs (including architectural guidelines and best practices) in the [BFF Documentation](http://eng-doc.int.s-cloud.net/guidelines/bff).
# Comment to be posted to on pull requests merged by a first time user
PRMergeComment: >
  Congrats on merging your pull request! What happens now? A pipeline will be triggered in [CI](https://ci.soundcloud.org/go/pipeline/activity/public-api-strangler). If everything goes well,
  your PR will be automatically deployed to production. Happy deployment!
  
commentOnLargePR:
  threshold: 300
  violationMessage: >-
    To speed up the review process we recommend keeping the PRs changes below 300 lines.
  fixMessage: >-
    Thank you for making the PR smaller!
