package com.soundcloud.publicApiStrangler.client.mothership.response.representation

sealed trait DeletePlaylistResponse

case object OkDeletePlaylistResponse extends DeletePlaylistResponse

case object NotAuthorizedDeletePlaylistResponse extends DeletePlaylistResponse

case object ForbiddenDeletePlaylistResponse extends DeletePlaylistResponse

case object InvalidUrnDeletePlaylistResponse extends DeletePlaylistResponse
