APP_BASE_URL="https://api.soundcloud.com"
APP_NAME="publicapistrangler"
AUTHENTICATOR_BASE_URL="http://authenticator.int.s-cloud.net"
AUTHSY_SRV_RECORD="dnssrv!http.api.prod.authsy.dd.srv.int.s-cloud.net"
GATEKEEPER_JSONCLIENT_REQUEST_TIMEOUT_MILLIS="50"
GATEKEEPER_SRV_RECORD="dnssrv!http.api.prod.gatekeeper.dd.srv.int.s-cloud.net"
GEOIP_BASE_URL="http://geoip.int.s-cloud.net"
JAVA_OPTS="-Xmx1G -Xms1G"
MEDIASERVICE_SRV_RECORD="dnssrv!http.urlgen.prod.media-service.dd.srv.int.s-cloud.net"
FOLLOWS_SRV_RECORD="dnssrv!http.api.prod.follows.dd.srv.int.s-cloud.net"
MEMCACHED_HOST="memcached"
MEMCACHED_PORT="11211"
MOSHIMOSHI_BASE_URL="http://moshimoshi.int.s-cloud.net"
MOTHERSHIP_API_SERVER_SRV_RECORD="dnssrv!lb.haproxy.prod.public-api.db.srv.int.s-cloud.net"
OKIDOKI_SRV_RECORD="dnssrv!http.okidoki.prod.moshimoshi.dd.srv.int.s-cloud.net"
PORT="5000"
PUBLICAPISTRANGLER_MAX_CONNS="60"
RATELIMIT_MAX_CONN="999999"
RATE_LIMIT_MEMCACHED_SERVERS="memcached"
MEMCACHED_TEST_HOST="memcached"
MEMCACHED_TEST_PORT="11211"
SEARCH_SRV_RECORD="dnssrv!http.dispatcher.prod.search.dd.srv.int.s-cloud.net"
TELE_PORT="5001"
TIMELINE_BASE_URL="dnssrv!http.api.prod.timeline.dd.srv.int.s-cloud.net"
ZIPKIN_HOST="zipkin.dev.s-cloud.net"
ZIPKIN_PORT="9410"
ZIPKIN_SAMPLE_RATE="0.001"
ZOOKEEPER_SERVERS="zookeeper:2181,zookeeper:2888,zookeeper:3888"
ENDPOINT_GROUP_SPECIFIC_RATE_LIMITS="15000 per PT24H for group 'plays' matching '(/i1)?/tracks/(.+)/stream.*'"
GENERAL_RATE_LIMITS="15000 per PT24H"
RATELIMITING_MAX_PROMETHEUS_COUNTER_LABELS="100"
RATELIMITING_JSONCLIENT_RETRIES="1"
RATELIMITING_JSONCLIENT_REQUEST_TIMEOUT_MILLIS="2000"
RATELIMITING_CIRCUITBREAKER_RESET_TIMEOUT_IN_MILLIS="1000"
RATELIMITING_CIRCUITBREAKER_MAX_CONSECUTIVE_FAILURES="5"
