APP_NAME=public-api-strangler
GRAPHITE_SERVER=graphite.int-test.s-cloud.net:2003
PORT=5000
TELE_PORT=5001
GRAPHITE_FLUSH_INTERVAL=60000
MOTHERSHIP_API_SERVER=dnssrv!lb.haproxy.test.public-api.ca.srv.int.s-cloud.net
ROLLOUT_BASE_URL="http://rollout.int.s-cloud.net"
AUTHSY_BASE_URL="http://authsy.int.s-cloud.net"
MEMCACHED_HOST="localhost"
MEMCACHED_PORT="11211"
GEOIP_BASE_URL="http://geoip.int.s-cloud.net"
AUTHENTICATOR_BASE_URL=http://authenticator.int.s-cloud.net