version: '2.3'

services:
  memcached:
    image: docker.localproxy.sc:42042/sc-memcached:release
    container_name: api_public_memcached
    ports:
      - "11211:11211"

  zookeeper:
    image: docker.localproxy.sc:42042/sc-zookeeper
    container_name: api_public_zk
    ports:
      - "2181:2181"

  # This container is only ever used by tests.
  apipublic:
    image: docker.localproxy.sc:42042/api-public:$VERSION
    command: bash -lex -c "./api --config=$CONFIG"
    healthcheck:
       test: [ "CMD", "curl", "-f", "http://localhost:5001/-/health" ]
       interval: 5s
       timeout: 10s
       retries: 30
    ports:
      - "5000:5000"
      - "5001:5001"
    links:
      - zookeeper:zookeeper
      - memcached:memcached

  asset-uploads:
    image: docker.localproxy.sc:42042/api-public-asset-uploads:$VERSION
    command: ./api --config=api-contract-test
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5005/-/health" ]
      interval: 5s
      timeout: 10s
      retries: 30
    ports:
      - "5005:5005"
    links:
      - apipublic:apipublic
    environment:
      https_proxy: 'http://proxy.localproxy.sc:42043'
    extra_hosts:
      - proxy.localproxy.sc:host-gateway
