---
memcached:
  image: memcached
  ports:
    - "11211:11211"

zookeeper:
  image: jplock/zookeeper:3.4.5
  ports:
    - "2181:2181"

dev:
  image: docker.dev.s-cloud.net/base-dev
  links:
    - memcached:memcached
    - zookeeper:zookeeper

# This container is only ever used by tests.
publicapistrangler:
  image: docker.dev.s-cloud.net/public-api-strangler:${PUBLIC_API_STRANGLER_VERSION}
  command: bash -lex -c "./api --config=default.sh"
  ports:
    - "${PORT}:5000"
    - "${TELE_PORT}:5001"
  environment:
    - DOCKER_IP=${DOCKER_IP}
  links:
    - memcached:memcached
    - zookeeper:zookeeper
