---
memcached:
  image: memcached
  ports:
    - "11211:11211"

zookeeper:
  image: docker.dev.s-cloud.net/sc-zookeeper
  ports:
    - "2181:2181"

dev:
  image: docker.dev.s-cloud.net/base-dev
  links:
    - memcached:memcached
    - zookeeper:zookeeper

# This container is only ever used by tests.
publicapistrangler:
  image: docker.dev.s-cloud.net/public-api-strangler:${PUBLIC_API_STRANGLER_VERSION}
  command: bash -lex -c "./api --config=development.sh"
  ports:
    - "5000:5000"
    - "5001:5001"
  environment:
    - DOCKER_IP=${DOCKER_IP}
  links:
    - memcached:memcached
    - zookeeper:zookeeper
    - publicapistub:publicapistub


publicapistub:
  image: docker.dev.s-cloud.net/ruby-2.3
  command: bash -ex -c "gem install sinatra ; ruby /tmp/pas/tools/public-api-stub.rb"
  volumes:
    - .:/tmp/pas
  ports:
    - "4567:4567"
