#####################################################################
#
# Project specific variables
#
#####################################################################

# This is the configuration that will be used for local testing
DEFAULT_CONFIG := default.sh

# This should be the same as the name in the manifest.json!!!
APP_NAME := public-api-strangler

# Here are the endpoints that can be run by this application.
API_ENTRYPOINT     := api
API_INSTANCE_COUNT := 100

BAZOOKA_CONFIG := production.enc
BAZOOKA_ZONES := db
RUNTIME_STACK := jdk-8
BUILD_STACK := jdk-8-dev

DEPLOY_SCRIPT ?= $(shell gen-deploy-script --arch=linux --name=public-api-strangler --revision=`artifact-manager package-version`)
PUBLIC_API_STRANGLER_VERSION ?= $(shell artifact-manager package-version)

#####################################################################

unit-test:
	crun $(BUILD_STACK) 'make unit-test'

end-to-end-test: remove-containers
	crun $(BUILD_STACK) 'env PUBLIC_API_STRANGLER_VERSION=$(PUBLIC_API_STRANGLER_VERSION) make end-to-end-test'

package: prepare-package-layout
	docker pull docker.dev.s-cloud.net/$(RUNTIME_STACK):latest
	artifact-manager package --runtime=$(RUNTIME_STACK)
	artifact-manager bazooka build --zones=$(BAZOOKA_ZONES) --runtime=$(RUNTIME_STACK) \
				 --proc="$(API_ENTRYPOINT) --config=$(BAZOOKA_CONFIG)"

prepare-package-layout:
	crun $(BUILD_STACK) 'make sc-debian-layout'
	gen-wrapper-script --target="bin/$(APP_NAME)" --wrapper=$(API_ENTRYPOINT)
	gen-postinst-script
	add-config config/$(DEFAULT_CONFIG)
	add-config config/$(BAZOOKA_CONFIG)

remove-containers:
	remove-containers

publish:
	artifact-manager publish
	artifact-manager bazooka publish --runtime=$(RUNTIME_STACK) --zones=$(BAZOOKA_ZONES)

promote-to-stable:
	artifact-manager promote stable
	artifact-manager bazooka promote stable --zones=$(BAZOOKA_ZONES)

promote-to-release:
	artifact-manager promote release
	artifact-manager bazooka promote release --zones=$(BAZOOKA_ZONES)

deploy-db:
	crun bazooka-cli "./$(DEPLOY_SCRIPT) bazooka --clean-revs \
		--boot-timeout=60s --health-port=app --health-path=/tracks/116540862?client_id=hannes_test \
		--bazooka-zone=db --scale-step=10 --instance-cnt=$(API_INSTANCE_COUNT) \
		--proc=api \
		--slack-channels=#core-services"

update-go-pipeline:
	go-pipeline update --config=pipeline.xml --group=core-services

sync-go-pipeline:
	go-pipeline get --name=public-api-strangler > pipeline.xml
	git diff pipeline.xml
