# This should be the same as the name in the manifest.json!!!
APP_NAME := public-api-strangler

API_ENTRYPOINT     := api
API_INSTANCE_COUNT := 100
APITRACKUPLOAD_ENTRYPOINT     := apitrackupload
APITRACKUPLOAD_INSTANCE_COUNT := 10

API_CONFIG := production_api.sh
APITRACKUPLOAD_CONFIG := production_apitrackupload.sh
BAZOOKA_ZONES := db
RUNTIME_STACK := jdk-8

DEPLOY_SCRIPT ?= $(shell gen-deploy-script --arch=linux --name=public-api-strangler --revision=`artifact-manager package-version`)
PUBLIC_API_STRANGLER_VERSION ?= $(shell artifact-manager package-version)

test:
	make test

package: prepare-package-layout
	docker pull docker.dev.s-cloud.net/$(RUNTIME_STACK):latest
	artifact-manager package --runtime=$(RUNTIME_STACK)
	artifact-manager bazooka build --zones=$(BAZOOKA_ZONES) --runtime=$(RUNTIME_STACK) \
				 --proc="$(API_ENTRYPOINT) --config=$(API_CONFIG)" \
				 --proc="$(APITRACKUPLOAD_ENTRYPOINT) --config=$(APITRACKUPLOAD_CONFIG)"

prepare-package-layout: patched-jdk
	crun sbt -- sbt scDebianLayout:packageBin
	gen-wrapper-script --target="bin/$(APP_NAME)" --wrapper=$(API_ENTRYPOINT)
	gen-wrapper-script --target="bin/$(APP_NAME)" --wrapper=$(APITRACKUPLOAD_ENTRYPOINT)
	gen-postinst-script
	add-config config/development
	add-config config/e2e
	add-config config/$(API_CONFIG)
	add-config config/$(APITRACKUPLOAD_CONFIG)
	rm -rf target/deb/srv/public-api-strangler/jdk/target
	mkdir -p target/deb/srv/public-api-strangler/jdk/target
	cp -r jdk/target target/deb/srv/public-api-strangler/jdk

.PHONY: patched-jdk
patched-jdk: jdk/target/sun/nio/ch/Util.class

jdk/target/sun/nio/ch/Util.class: jdk/src/share/classes/sun/nio/ch/Util.java
	mkdir -p jdk/target
	crun jdk-8 -- javac -d jdk/target $<

publish:
	artifact-manager publish
	artifact-manager bazooka publish --runtime=$(RUNTIME_STACK) --zones=$(BAZOOKA_ZONES)

promote-to-stable:
	artifact-manager promote stable
	artifact-manager bazooka promote stable --zones=$(BAZOOKA_ZONES)

promote-to-release:
	artifact-manager promote release
	artifact-manager bazooka promote release --zones=$(BAZOOKA_ZONES)

.PHONY: deploy-db-api
deploy-db-api:
	crun bazooka-cli "./$(DEPLOY_SCRIPT) bazooka --clean-revs \
		--boot-timeout=60s --health-port=app --health-path=/tracks/116540862?client_id=hannes_test \
		--bazooka-zone=db --scale-step=10 --instance-cnt=$(API_INSTANCE_COUNT) \
		--proc=$(API_ENTRYPOINT) \
		--slack-channels=#core-services"

.PHONY: deploy-db-apitrackupload
deploy-db-apitrackupload:
	crun bazooka-cli "./$(DEPLOY_SCRIPT) bazooka --clean-revs \
		--boot-timeout=60s --health-port=app --health-path=/tracks/116540862?client_id=hannes_test \
		--bazooka-zone=db --scale-step=10 --instance-cnt=$(APITRACKUPLOAD_INSTANCE_COUNT) \
		--proc=$(APITRACKUPLOAD_ENTRYPOINT) \
		--slack-channels=#core-services"

update-go-pipeline:
	go-pipeline update --config=pipeline.xml --group=core-services

sync-go-pipeline:
	go-pipeline get --name=public-api-strangler > pipeline.xml
	git diff pipeline.xml
