---
format_version: 2
pipelines:
  public-api-strangler-pr:
    group: backend-engineering-productivity-pr
    label_template: "${COUNT}-${git[:7]}"
    materials:
      git:
        scm: public-api-strangler-pr
    stages:
    - test:
        jobs:
          unit-tests:
            tasks:
            - exec:
                command: make
                arguments:
                - unit-test
                - package
                - publish
          asset-uploader-unit-tests:
            tasks:
            - exec:
                command: make
                arguments:
                - -C
                - asset-uploads
                - test-unit
    - end-to-end-tests:
        jobs:
          end-to-end-tests:
            tasks:
            - exec:
                command: make
                arguments:
                - end-to-end-test
          asset-uploader-integration-tests:
            tasks:
            - exec:
                command: make
                arguments:
                - -C
                - asset-uploads
                - test-integration
