---
format_version: 2
pipelines:
  api-public-pr:
    group: devices-team
    label_template: "${COUNT}-${git[:7]}"
    materials:
      git:
        scm: api-public-pr
    stages:
    - test:
        jobs:
          lint:
            tasks:
            - exec:
                command: make
                arguments:
                - lint
          unit-test:
            tasks:
            - exec:
                command: make
                arguments:
                - unit-test
          asset-uploader-unit-tests:
            tasks:
            - exec:
                command: make
                arguments:
                - -C
                - asset-uploads
                - test-unit
          check-prometheus:
            tasks:
            - exec:
                command: make
                arguments:
                - check-prometheus
    - end-to-end-tests:
        jobs:
          end-to-end-tests:
            tasks:
            - exec:
                command: make
                arguments:
                - package
                - end-to-end-test
          asset-uploader-integration-tests:
            tasks:
            - exec:
                command: make
                arguments:
                - -C
                - asset-uploads
                - test-integration
          contract-test:
            tasks:
            - exec:
                command: make
                arguments:
                - contract-test
