---
format_version: 2
pipelines:
  public-api-strangler-memcached:
    group: core-services
    label_template: "${COUNT}-${git[:7]}"
    materials:
      git:
        git: git@github.com:soundcloud/sc-k8s-memcached.git
    stages:
    - deploy:
        approval: manual
        jobs:
          deploy-db:
            job_type: deploy
            tasks:
            - exec:
                command: make
                arguments:
                - deploy
                - scale
                - ZONE=db
                - SYSTEM=public-api-strangler
                - CPU=0.2
                - STORAGE=512
                - REPLICAS=10
          deploy-et:
            job_type: deploy
            tasks:
            - exec:
                command: make
                arguments:
                - deploy
                - scale
                - ZONE=et
                - SYSTEM=public-api-strangler
                - CPU=0.2
                - STORAGE=512
                - REPLICAS=10
