---
format_version: 2
pipelines:
  public-api-strangler-asset-uploads:
    group: backend-engineering-productivity
    label_template: "${COUNT}-${git[:7]}"
    materials:
      git:
        git: git@github.com:soundcloud/public-api-strangler.git
        whitelist:
        - asset-uploads/**/*
    stages:
    - test:
        jobs:
          run-tests-and-publish:
            tasks:
            - exec:
                command: make
                arguments:
                - -C
                - asset-uploads
                - test
            - exec:
                command: make
                arguments:
                - -C
                - asset-uploads
                - publish
    - publish-deploy:
        jobs:
          publish-deploy-db:
            job_type: deploy
            environment_variables:
              ENV: production
              ZONE: db
            tasks:
            - exec:
                command: make
                arguments:
                - -C
                - asset-uploads
                - publish-deploy
    - promote:
        jobs:
          promote:
            job_type: deploy
            tasks:
            - exec:
                command: make
                arguments:
                - -C
                - asset-uploads
                - promote-to-stable
                - promote-to-release
    - deploy:
        jobs:
          deploy-db:
            job_type: deploy
            environment_variables:
              ENV: production
              ZONE: db
            tasks:
            - exec:
                command: make
                arguments:
                - -C
                - asset-uploads
                - deploy
