---
format_version: 2
pipelines:
  public-api-strangler:
    group: core-clients
    label_template: "${COUNT}-${git[:7]}"
    materials:
      git:
        git: git@github.com:soundcloud/public-api-strangler.git
        # There is a separate pipeline for the asset-uploads-api component.
        blacklist:
        - asset-uploads/**/*
    stages:
    - test:
        jobs:
          unit-tests-and-publish:
            tasks:
            - exec:
                command: make
                arguments:
                - lint
            - exec:
                command: make
                arguments:
                - unit-test
            - exec:
                command: make
                arguments:
                - package
            - exec:
                command: make
                arguments:
                - publish
    - end-to-end-tests:
        jobs:
          end-to-end-tests:
            tasks:
            - exec:
                command: make
                arguments:
                - end-to-end-test
    - publish-deploy:
        jobs:
          publish-deploy-db:
            job_type: deploy
            environment_variables:
              ZONE: db
            tasks:
            - exec:
                command: make
                arguments:
                - publish-deploy
          publish-deploy-et:
            job_type: deploy
            environment_variables:
              ZONE: et
            tasks:
            - exec:
                command: make
                arguments:
                - publish-deploy
    - promote-to-stable:
        jobs:
          promote-to-stable:
            tasks:
            - exec:
                command: make
                arguments:
                - promote-to-stable
                - promote-to-release
    - canary:
        jobs:
          canary-api:
            job_type: deploy
            environment_variables:
              ZONE: db
            tasks:
            - exec:
                command: make
                arguments:
                - canary-api
    - deploy-to-production:
        jobs:
          deploy-db:
            job_type: deploy
            environment_variables:
              ZONE: db
            tasks:
            - exec:
                command: make
                arguments:
                - deploy-api
          deploy-et:
            job_type: deploy
            environment_variables:
              ZONE: et
            tasks:
            - exec:
                command: make
                arguments:
                - deploy-api
    - deploy-doc:
      jobs:
        deploy:
          tasks:
          - exec:
              command: make
              arguments:
              - package
              - publish
              - publish-deploy
              - promote
              - deploy
              working_directory: doc