APP_BASE_URL="https://api.soundcloud.com"
APP_NAME="public-api-strangler"
AUTHENTICATOR_BASE_URL="http://authenticator.int.s-cloud.net"
AUTHSY_SRV_RECORD="dnssrv!http.api.prod.authsy.dd.srv.int.s-cloud.net"
FINAGLE_METRICS_ENABLED="true"
GATEKEEPER_JSONCLIENT_REQUEST_TIMEOUT_MILLIS="50"
GATEKEEPER_SRV_RECORD="dnssrv!http.api.prod.gatekeeper.dd.srv.int.s-cloud.net"
GEOIP_BASE_URL="http://geoip.int.s-cloud.net"
JAVA_OPTS="-XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:NewRatio=1 -Xmx1G -Xms1G -XX:ParallelGCThreads=2 -Dcom.twitter.jvm.numProcs=2"
MEDIASERVICE_SRV_RECORD="dnssrv!http.urlgen.prod.media-service.dd.srv.int.s-cloud.net"
MEMCACHED_HOST="ip-10-33-33-60.m02.ams5.s-cloud.net,ip-10-33-21-49.n07.ams5.s-cloud.net"
MEMCACHED_PORT="11211"
MOSHIMOSHI_BASE_URL="http://moshimoshi.int.s-cloud.net"
MOTHERSHIP_API_SERVER_SRV_RECORD="dnssrv!lb.haproxy.prod.public-api.db.srv.int.s-cloud.net"
OKIDOKI_SRV_RECORD="dnssrv!http.okidoki.prod.moshimoshi.dd.srv.int.s-cloud.net"
RATELIMIT_MAX_CONN="999999"
RATE_LIMIT_MEMCACHED_SERVERS="ip-10-33-33-60.m02.ams5.s-cloud.net:11211,ip-10-33-21-49.n07.ams5.s-cloud.net:11211"
TIMELINE_BASE_URL="dnssrv!http.api.prod.timeline.dd.srv.int.s-cloud.net"
ZIPKIN_HOST="zipkin.dev.s-cloud.net"
ZIPKIN_PORT="9410"
ZIPKIN_SAMPLE_RATE="0.001"
