APP_NAME="public-api-strangler"
PORT="5000"
RATELIMIT_MAX_PER_IP="999999"
TELE_PORT="5001"
GRAPHITE_FLUSH_INTERVAL="60000"
GRAPHITE_SERVER="graphite.int.s-cloud.net:2003"
JAVA_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -Xms700M -Xmx700M"
MOTHERSHIP_API_SERVER="dnssrv!lb.haproxy.prod.public-api.ca.srv.int.s-cloud.net"
RATE_LIMIT_MEMCACHED_SERVERS="ip-10-33-33-60.m02.ams5.s-cloud.net:11211,ip-10-33-21-49.n07.ams5.s-cloud.net:11211"
ROLLOUT_BASE_URL="http://rollout.int.s-cloud.net"
AUTHSY_BASE_URL="http://authsy.int.s-cloud.net"
MEMCACHED_HOST="ip-10-33-33-60.m02.ams5.s-cloud.net,ip-10-33-21-49.n07.ams5.s-cloud.net"
MEMCACHED_PORT="11211"
GEOIP_BASE_URL="http://geoip.int.s-cloud.net"
AUTHENTICATOR_BASE_URL=http://authenticator.int.s-cloud.net
ZIPKIN_HOST="zipkin.dev.int.s-cloud.net"
ZIPKIN_PORT="9410"
ZIPKIN_SAMPLE_RATE="0.01"
