syntax = "proto3";

package com.soundcloud.hocuspocus;

// we can't use a fully qualified import path for go_package;
// it produces weirdness with Go modules.
// Upstream discussions:
// - https://github.com/twitchtv/twirp/issues/169
// - https://github.com/golang/protobuf/issues/748

option go_package = "hocuspocus";

// Will be lowercased and used in the path name. Field names must match /[A-Z]+/
enum Kind {
  UNKNOWN   = 0;
  ARTWORKS  = 1; // Track and Playlist display image
  AVATARS   = 2; // Profile display image
  ICONS     = 3; // OAuth application profile
  VISUALS   = 4; // Profile header customization
  PRODUCTS  = 5; // Off-Platform distribution images
}


// Raw is a image that hasn't been validated, or stored
message Raw {
  // The kind/class
  Kind kind = 1;

  // The body of the image
  bytes image = 2;
}

message Image {
  Kind kind = 1;

  int32 width = 2;
  int32 height = 3;

  string content_type = 4; // like image/jpeg or image/gif
  string resize_url = 5; // like http://i.cdn.com/image-original.jpg
  string origin_uri = 6; // like s3://bucket/image-original.jpg or gs://bucket/image-original.jpg
}

// Hocuspocus handles all the image magic at SoundCloud
service Hocuspocus {
  // Stores an image.
  // Error codes:
  // - `unavailable` when errors occur while writing to storage.
  // - `invalid_argument` for bad image Kinds (shouldn't happen, that's why we've got enums)
  // - `internal` for bugs
  rpc StoreImage(Raw) returns (Image);
};


