package com.soundcloud.publicApiStrangler.representation

sealed trait AddToPlaylistResponse

case object OkAddToPlaylistResponse extends AddToPlaylistResponse

case object NotAuthorizedAddToPlaylistResponse extends AddToPlaylistResponse

case object InvalidUrnAddToPlaylistResponse extends AddToPlaylistResponse

case object TrackAlreadyInPlaylistAddToPlaylistResponse extends AddToPlaylistResponse
