package com.soundcloud.publicApiStrangler.representation

sealed trait DeleteFromPlaylistResponse

case object OkDeleteFromPlaylistResponse extends DeleteFromPlaylistResponse

case object NotAuthorizedDeleteFromPlaylistResponse extends DeleteFromPlaylistResponse

case object InvalidUrnDeleteFromPlaylistResponse extends DeleteFromPlaylistResponse
