package com.soundcloud.publicApiStrangler.representation

sealed trait DeleteUserResponse

case object OkDeleteUserResponse extends DeleteUserResponse

case object InvalidParametersDeleteUserResponse extends DeleteUserResponse

case object UserNotFoundDeleteUserResponse extends DeleteUserResponse