package com.soundcloud.publicApiStrangler.representation

import com.soundcloud.jvmkit.module.util.Urn


case class SimilarSounds(similarTracks: Iterable[Urn], meta: SimilarSoundsMeta)

/**
  * Meta information from similar sounds backend
  *
  * @param variant       query parameter echoed back from backend when doing A/B tests
  * @param sourceVersion model(fallback) used on backend to process this request
  * @param queryUrn      either echoed back from request or newly generated by backend if not provided on request
  */
case class SimilarSoundsMeta(page: Int,
                             pageSize: Int,
                             variant: String,
                             sourceVersion: String,
                             queryUrn: Urn,
                             previousHref: String,
                             nextHref: String)
