package com.soundcloud.publicApiStrangler.representation

sealed trait UpdateUserResponse

case object OkUpdateUserResponse extends UpdateUserResponse

case object NotAuthorizedUpdateUserResponse extends UpdateUserResponse

case object InvalidUrnUpdateUserResponse extends UpdateUserResponse
