[scala]
  version: ${sbt.scala.version-auto}

[app]
  org: ${sbt.organization-org.scala-sbt}
  name: sbt
  version: 0.13.9
  class: ${sbt.main.class-sbt.xMain}
  components: xsbti,extra
  cross-versioned: ${sbt.cross.versioned-false}

# The repositories defined here are only used for downloading / bootstrapping sbt itself.
# It makes sure we download everything through our internal proxy and don't go out to the Internet.
[repositories]
  local
  soundcloud-proxy: http://maven.int.s-cloud.net/content/groups/soundcloud-proxy/
  second-soundcloud-proxy: http://maven.int.s-cloud.net/content/groups/soundcloud-proxy/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
[boot]
  directory: ${sbt.boot.directory-${sbt.global.base-${user.home}/.sbt}/boot/}

[ivy]
  ivy-home: ${user.dir}/.ivy2
