#!/usr/bin/env bash

gh api -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GH_TOKEN" /repos/soundcloud/api/releases -F tag_name=$(date "+%Y-%m-%d") -F name=$(date "+%Y-%m-%d") -F body=@RELEASE_NOTES.md
