package com.soundcloud.publicApiStrangler.test.util

import com.soundcloud.jvmkit.module.util.Urn
import com.soundcloud.publicApiStrangler.client.trackmetadata.{Artwork, EmbeddingPermission, Track}
import org.joda.time.LocalDateTime

case class TrackMetadataTrackBuilder(urn: Urn = Urn("soundcloud:tracks:1"),
                                     user_urn: Urn = Urn("soundcloud:users:1"),
                                     commentable: Boolean = false,
                                     description: Option[String] = Some("description"),
                                     created_at: LocalDateTime = LocalDateTime.now(),
                                     disabled_at: Option[LocalDateTime] = None,
                                     downloadable: Option[Boolean] = None,
                                     duration: Int = 0,
                                     genre: Option[String] = None,
                                     last_modified: LocalDateTime = LocalDateTime.now(),
                                     permalink: String = "permalink",
                                     permalink_url: Option[String] = Some("permalink_url"),
                                     public: Boolean = true,
                                     secret_token: String = "secret_token",
                                     user_tags: List[String] = List("tag", "another_tag"),
                                     machine_tags: List[String] = List.empty,
                                     title: String = "title",
                                     uid: Option[String] = Some("uid"),
                                     api_streamable: Option[Boolean] = None,
                                     streamable: Option[Boolean] = None,
                                     reveal_comments: Boolean = false,
                                     reveal_stats: Boolean = false,
                                     label_name: Option[String] = Some("label_name"),
                                     license: String = null,
                                     embeddable: Option[Boolean] = None,
                                     release_year: Option[Int] = None,
                                     release_month: Option[Int] = None,
                                     release_day: Option[Int] = None,
                                     embeddableBy: EmbeddingPermission = EmbeddingPermission.None,
                                     releaseDate: Option[LocalDateTime] = None,
                                     artwork: Artwork = Artwork(Some("artwork")),
                                     published_at: Option[LocalDateTime] = None,
                                     purchase_url: Option[String] = Some("purchase_url"),
                                     purchase_title: Option[String] = Some("purchase_title"),
                                     bpm: Option[Double] = None,
                                     track_type: Option[String] = Some("track_type"),
                                     release: Option[String] = Some("release"),
                                     key_signature: Option[String] = Some("key_signature"),
                                     video_url: Option[String] = Some("video_url"),
                                     label_id: Option[Int] = None,
                                     supply_chain_status: Option[String] = Some("manual_upload")) {

  def build: Track = {
    Track(
      urn = urn,
      user_urn = user_urn,
      commentable = commentable,
      description = description,
      created_at = created_at,
      disabled_at = disabled_at,
      downloadable = downloadable,
      duration = duration,
      genre = genre,
      last_modified = last_modified,
      permalink = permalink,
      permalink_url = permalink_url,
      public = public,
      secret_token = secret_token,
      user_tags = user_tags,
      machine_tags = machine_tags,
      title = title,
      uid = uid,
      api_streamable = api_streamable,
      streamable = streamable,
      reveal_comments = reveal_comments,
      reveal_stats = reveal_stats,
      label_name = label_name,
      license = license,
      embeddable = embeddable,
      release_year = release_year,
      release_month = release_month,
      release_day = release_day,
      embeddableBy = embeddableBy,
      releaseDate = releaseDate,
      artwork = artwork,
      published_at = published_at,
      purchase_url = purchase_url,
      purchase_title = purchase_title,
      bpm = bpm,
      track_type = track_type,
      release = release,
      key_signature = key_signature,
      video_url = video_url,
      label_id = label_id,
      supply_chain_status = supply_chain_status)
  }
}
