package com.soundcloud.apipublic.client.trackcoordinator

import play.api.libs.json.JsonNaming.SnakeCase
import play.api.libs.json._

case class PublisherMetadata(isrc: Option[String], artist: Option[String])

object PublisherMetadata {
  private val snakeCase = Json.configured(JsonConfiguration(SnakeCase))
  implicit val format: Format[PublisherMetadata] = snakeCase.format
}

case class TrackCoordinatorTrack(
    api_streamable: Option[Boolean],
    artwork_url: Option[String],
    bpm: Option[Int],
    comment_count: Int,
    commentable: Boolean,
    created_at: String,
    description: Option[String],
    download_url: String,
    downloadable: Option[Boolean],
    downloads_count: Option[Int],
    duration: Int,
    embeddable_by: String,
    embeddable: Option[Boolean],
    favoritings_count: Int,
    genre: Option[String],
    geo_blockings: Option[List[String]],
    isrc: Option[String],
    key_signature: Option[String],
    label_id: Option[Int],
    label_name: Option[String],
    last_modified: String,
    license: String,
    original_content_size: Option[Int],
    original_format: Option[String],
    permalink: String,
    permalink_url: String,
    playback_count: Int,
    public: Boolean,
    publisher_metadata: Option[PublisherMetadata],
    purchase_title: Option[String],
    purchase_url: Option[String],
    release: Option[String],
    release_day: Option[Int],
    release_month: Option[Int],
    release_year: Option[Int],
    reveal_comments: Boolean,
    reveal_stats: Boolean,
    secret_token: Option[String], // not optional from track coordinator but without this CreatedTrack Writes does not compile :(
    sharing: String,
    state: String,
    stream_url: String,
    streams_url: String,
    streamable: Boolean,
    tag_list: Option[String],
    title: String,
    track_type: Option[String],
    uri: String,
    urn: String,
    user_playback_count: Option[Int] = Some(1), // Was hardcoded in the public api (https://github.com/soundcloud/soundcloud/blob/74c72f348f50b64e0e6fccd4bbd1c963249dc33b/app/resources/api/track_resource.rb#L91)
    user_urn: String,
    video_url: Option[String],
    waveform_url: String
)

object TrackCoordinatorTrack {
  implicit val format = new Format[TrackCoordinatorTrack] {

    override def writes(o: TrackCoordinatorTrack) = {
      Json.obj(
        "artwork_url" -> Json.toJson(o.artwork_url),
        "bpm" -> Json.toJson(o.bpm),
        "commentable" -> Json.toJson(o.commentable),
        "comment_count" -> Json.toJson(o.comment_count),
        "created_at" -> Json.toJson(o.created_at),
        "description" -> Json.toJson(o.description),
        "download_url" -> Json.toJson(o.download_url),
        "downloadable" -> Json.toJson(o.downloadable),
        "downloads_count" -> Json.toJson(o.downloads_count),
        "duration" -> Json.toJson(o.duration),
        "embeddable_by" -> Json.toJson(o.embeddable_by),
        "embeddable" -> Json.toJson(o.embeddable),
        "favoritings_count" -> Json.toJson(o.favoritings_count),
        "genre" -> Json.toJson(o.genre),
        "geo_blockings" -> Json.toJson(o.geo_blockings),
        "isrc" -> Json.toJson(o.isrc),
        "key_signature" -> Json.toJson(o.key_signature),
        "label_id" -> Json.toJson(o.label_id),
        "label_name" -> Json.toJson(o.label_name),
        "last_modified" -> Json.toJson(o.last_modified),
        "license" -> Json.toJson(o.license),
        "original_content_size" -> Json.toJson(o.original_content_size),
        "original_format" -> Json.toJson(o.original_format),
        "permalink" -> Json.toJson(o.permalink),
        "permalink_url" -> Json.toJson(o.permalink_url),
        "playback_count" -> Json.toJson(o.playback_count),
        "public" -> Json.toJson(o.public),
        "publisher_metadata" -> Json.toJson(o.publisher_metadata),
        "purchase_title" -> Json.toJson(o.purchase_title),
        "purchase_url" -> Json.toJson(o.purchase_url),
        "release" -> Json.toJson(o.release),
        "release_day" -> Json.toJson(o.release_day),
        "release_month" -> Json.toJson(o.release_month),
        "release_year" -> Json.toJson(o.release_year),
        "reveal_comments" -> Json.toJson(o.reveal_comments),
        "reveal_stats" -> Json.toJson(o.reveal_stats),
        "secret_token" -> Json.toJson(o.secret_token),
        "sharing" -> Json.toJson(o.sharing),
        "state" -> Json.toJson(o.state),
        "stream_url" -> Json.toJson(o.stream_url),
        "streams_url" -> Json.toJson(o.streams_url),
        "streamable" -> Json.toJson(o.api_streamable),
        "tag_list" -> Json.toJson(o.tag_list),
        "title" -> Json.toJson(o.title),
        "track_type" -> Json.toJson(o.track_type),
        "uri" -> Json.toJson(o.uri),
        "urn" -> Json.toJson(o.urn),
        "user_playback_count" -> Json.toJson(o.user_playback_count),
        "user_urn" -> Json.toJson(o.user_urn),
        "video_url" -> Json.toJson(o.video_url),
        "waveform_url" -> Json.toJson(o.waveform_url)
      )
    }

    override def reads(json: JsValue): JsResult[TrackCoordinatorTrack] = JsSuccess {
      TrackCoordinatorTrack(
        api_streamable = (json \ "api_streamable").asOpt[Boolean],
        artwork_url = (json \ "artwork_url").asOpt[String],
        bpm = (json \ "bpm").asOpt[Int],
        comment_count = (json \ "comments_count").as[Int],
        commentable = (json \ "commentable").as[Boolean],
        created_at = (json \ "created_at").as[String],
        description = (json \ "description").asOpt[String],
        download_url = (json \ "download_url").as[String],
        downloadable = (json \ "downloadable").asOpt[Boolean],
        downloads_count = (json \ "downloads_count").asOpt[Int],
        duration = (json \ "duration").as[Int],
        embeddable_by = (json \ "embeddable_by").as[String],
        embeddable = (json \ "embeddable").asOpt[Boolean],
        favoritings_count = (json \ "favoritings_count").as[Int],
        genre = (json \ "genre").asOpt[String],
        geo_blockings = (json \ "geo_blockings").asOpt[List[String]],
        isrc = (json \ "isrc").asOpt[String],
        key_signature = (json \ "key_signature").asOpt[String],
        label_id = (json \ "label_id").asOpt[Int],
        label_name = (json \ "label_name").asOpt[String],
        last_modified = (json \ "last_modified").as[String],
        license = (json \ "license").as[String],
        original_content_size = (json \ "original_content_size").asOpt[Int],
        original_format = (json \ "original_format").asOpt[String],
        permalink = (json \ "permalink").as[String],
        permalink_url = (json \ "permalink_url").as[String],
        playback_count = (json \ "playback_count").as[Int],
        public = (json \ "public").as[Boolean],
        publisher_metadata = (json \ "publisher_metadata").asOpt[PublisherMetadata],
        purchase_title = (json \ "purchase_title").asOpt[String],
        purchase_url = (json \ "purchase_url").asOpt[String],
        release = (json \ "release").asOpt[String],
        release_day = (json \ "release_day").asOpt[Int],
        release_month = (json \ "release_month").asOpt[Int],
        release_year = (json \ "release_year").asOpt[Int],
        reveal_comments = (json \ "reveal_comments").as[Boolean],
        reveal_stats = (json \ "reveal_stats").as[Boolean],
        secret_token = (json \ "secret_token").asOpt[String],
        sharing = (json \ "sharing").as[String],
        state = (json \ "state").as[String],
        stream_url = (json \ "stream_url").as[String],
        streams_url = (json \ "streams_url").as[String],
        streamable = (json \ "streamable").as[Boolean],
        tag_list = (json \ "tag_list").asOpt[String],
        title = (json \ "title").as[String],
        track_type = (json \ "track_type").asOpt[String],
        uri = (json \ "uri").as[String],
        urn = (json \ "urn").as[String],
        user_urn = (json \ "user_urn").as[String],
        video_url = (json \ "video_url").asOpt[String],
        waveform_url = (json \ "waveform_url").as[String]
      )
    }
  }
}
