package com.soundcloud.publicApiStrangler.mapper.similarsounds

import com.soundcloud.jvmkit.module.util.Urn

case class SimilarSounds(similarTracks: Iterable[Urn], meta: SimilarSoundsMeta)

/**
  * Meta information from similar sounds backend
  *
  * @param sourceVersion model(fallback) used on backend to process this request
  * @param queryUrn      generated by backend
  */
case class SimilarSoundsMeta(pageSize: Int,
                             variant: String,
                             sourceVersion: String,
                             queryUrn: Urn)
