---
name: asset-uploads
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - ".github/workflows/asset-uploads.yml"
    - asset-uploads/**/*
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-main"
jobs:
  call_api_public_asset_uploads_commons:
    name: call asset-uploads-common workflow
    uses: "./.github/workflows/asset-uploads-common.yml"
    secrets: inherit
    with:
      ref: ${{ github.ref }}
