---
name: asset-uploads
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: 'The ref that triggered the workflow'
        type: string
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
concurrency:
  group: "${{ github.workflow }}-${{ inputs.ref }}-common"
jobs:
  call_api_public_asset_uploads_test:
    name: call asset-uploads-test workflow
    uses: "./.github/workflows/asset-uploads-test.yml"
    secrets: inherit
    with:
      ref: ${{ inputs.ref }}
  call_api_public_asset_uploads_publish_deploy:
    name: call asset-uploads-publish-deploy workflow
    uses: "./.github/workflows/asset-uploads-publish-deploy.yml"
    secrets: inherit
    needs: call_api_public_asset_uploads_test
    with:
      ref: ${{ inputs.ref }}
  call_api_public_asset_uploads_promote:
    name: call asset-uploads-promote workflow
    uses: "./.github/workflows/asset-uploads-promote.yml"
    secrets: inherit
    needs: call_api_public_asset_uploads_publish_deploy
    with:
      ref: ${{ inputs.ref }}
  call_api_public_asset_uploads_deploy:
    name: call asset-uploads-deploy workflow
    uses: "./.github/workflows/asset-uploads-deploy.yml"
    secrets: inherit
    needs: call_api_public_asset_uploads_promote
    with:
      ref: ${{ inputs.ref }}
