name: deploy-to-production
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: 'The ref that triggered the workflow'
        type: string
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
concurrency:
  group: "${{ github.workflow }}-${{ inputs.ref }}-deploy-to-production"
jobs:
  deploy-db:
    env:
      ZONES: db
    runs-on:
    - self-hosted
    - i-deploy-prod
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Set up sc-tools
      uses: soundcloud/sc-github-actions/sc-tools@master
    - name: make deploy-api
      run: make deploy-api
    permissions:
      contents: read
      id-token: write
  deploy-replicas:
    env:
      ZONES: replicas
    runs-on:
    - self-hosted
    - i-deploy-prod
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Set up sc-tools
      uses: soundcloud/sc-github-actions/sc-tools@master
    - name: make deploy-api
      run: make deploy-api
    permissions:
      contents: read
      id-token: write
