---
name: publish-release
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: 'Git ref to publish (branch, tag, or full commit SHA)'
        type: string
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
concurrency:
  group: "${{ github.workflow }}-${{ inputs.ref }}-publish-release"
jobs:
  publish-release:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ inputs.ref }}
    - name: Set up sc-tools
      uses: soundcloud/sc-github-actions/sc-tools@master
    - name: publish release notes and OpenAPI
      env:
        GH_TOKEN: ${{ secrets.SC_GITHUB_BOT_PAT }}
      run: |
        git diff-index --exit-code HEAD~1 RELEASE_NOTES.md && echo 'No release notes to publish...' && exit 0
        ./scripts/release
