---
name: test
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: 'The ref that triggered the workflow'
        type: string
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
concurrency:
  group: "${{ github.workflow }}-${{ inputs.ref }}-test"
jobs:
  lint:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Set up sc-tools
      uses: soundcloud/sc-github-actions/sc-tools@master
    - name: make lint
      run: make lint
  unit-test:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Set up sc-tools
      uses: soundcloud/sc-github-actions/sc-tools@master
    - name: make unit-test
      run: make unit-test
  publish:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Set up sc-tools
      uses: soundcloud/sc-github-actions/sc-tools@master
    - name: make package publish
      run: make package publish
  check-prometheus:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Set up sc-tools
      uses: soundcloud/sc-github-actions/sc-tools@master
    - name: make check-prometheus
      run: make check-prometheus
