---
name: api-public-end-to-end-tests
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-end-to-end-tests"
jobs:
  end-to-end-tests:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: sc-setup
      uses: soundcloud/sc-github-actions/sc-setup@master
      with:
        sc-tools: 'true'
    - name: make end-to-end-test
      run: make end-to-end-test
  contract-tests:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: sc-setup
      uses: soundcloud/sc-github-actions/sc-setup@master
      with:
        sc-tools: 'true'
    - name: make contract-test
      run: make contract-test
