---
name: api-public-deploy-to-production
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-deploy-to-production"
jobs:
  deploy-db:
    env:
      ZONES: db
    runs-on:
    - self-hosted
    - i-deploy-prod
    steps:
    - name: sc-setup
      uses: soundcloud/sc-github-actions/sc-setup@master
      with:
        sc-tools: 'true'
    - name: make deploy-api
      run: make deploy-api
  deploy-replicas:
    env:
      ZONES: replicas
    runs-on:
    - self-hosted
    - i-deploy-prod
    steps:
    - name: sc-setup
      uses: soundcloud/sc-github-actions/sc-setup@master
      with:
        sc-tools: 'true'
    - name: make deploy-api
      run: make deploy-api
