---
name: api-public-promote-to-stable
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-promote-to-stable"
jobs:
  promote-to-stable:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: sc-setup
      uses: soundcloud/sc-github-actions/sc-setup@master
      with:
        sc-tools: 'true'
    - name: make promote-to-stable promote-to-release
      run: make promote-to-stable promote-to-release
