---
name: api-public-asset-uploads
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - ".github/workflows/workflow-api-public-asset-uploads.yml"
    - asset-uploads/**/*
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-main"
jobs:
  call_api_public_asset_uploads_test:
    name: call api-public-asset-uploads-test workflow
    uses: "./.github/workflows/workflow-api-public-asset-uploads-test.yml"
    secrets: inherit
  call_api_public_asset_uploads_publish_deploy:
    name: call api-public-asset-uploads-publish-deploy workflow
    uses: "./.github/workflows/workflow-api-public-asset-uploads-publish-deploy.yml"
    secrets: inherit
    needs: call_api_public_asset_uploads_test
  call_api_public_asset_uploads_promote:
    name: call api-public-asset-uploads-promote workflow
    uses: "./.github/workflows/workflow-api-public-asset-uploads-promote.yml"
    secrets: inherit
    needs: call_api_public_asset_uploads_publish_deploy
  call_api_public_asset_uploads_deploy:
    name: call api-public-asset-uploads-deploy workflow
    uses: "./.github/workflows/workflow-api-public-asset-uploads-deploy.yml"
    secrets: inherit
    needs: call_api_public_asset_uploads_promote
