---
name: api-public-asset-uploads-test
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: 'The ref that triggered the workflow'
        type: string
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
concurrency:
  group: "${{ github.workflow }}-${{ inputs.ref }}-test"
jobs:
  run-tests-and-publish:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Set up sc-tools
      uses: soundcloud/sc-github-actions/sc-tools@master
    - name: make -C asset-uploads test
      run: make -C asset-uploads test
    - name: make -C asset-uploads publish
      run: make -C asset-uploads publish
