---
name: api-public-end-to-end-tests
env:
  SC_PIPELINE_GROUP: api-team
on:
  schedule:
    - cron: "0 10 * * *" # once a day @ 10 AM UTC
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: 'The ref that triggered the workflow'
        type: string
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
concurrency:
  group: "${{ github.workflow }}-${{ inputs.ref }}-end-to-end-tests"
jobs:
  end-to-end-tests:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Set up sc-tools
      uses: soundcloud/sc-github-actions/sc-tools@master
    - name: make end-to-end-test
      run: make end-to-end-test
    - name: make post e2e success to slack
      run: make post-to-slack
  contract-tests:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - name: Set up sc-tools
      uses: soundcloud/sc-github-actions/sc-tools@master
    - name: make contract-test
      run: make contract-test
