---
name: api-public
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths-ignore:
    - asset-uploads/**/*
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-${{ github.run_number }}-main"
jobs:
  call_api_public_common:
    name: call api-public-common workflow
    uses: "./.github/workflows/workflow-api-public-common.yml"
    secrets: inherit
    with:
      ref: ${{ github.ref }}
