---
name: api-public-asset-uploads-deploy
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-deploy"
jobs:
  deploy-db:
    env:
      ENV: production
      ZONES: primary,replicas
    runs-on:
    - self-hosted
    - i-deploy-prod
    steps:
    - name: sc-setup
      uses: soundcloud/sc-github-actions/sc-setup@master
      with:
        sc-tools: 'true'
    - name: make -C asset-uploads deploy
      run: make -C asset-uploads deploy
