---
name: api-public-test
env:
  SC_PIPELINE_GROUP: api-team
on:
  workflow_dispatch:
  workflow_call:
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-test"
jobs:
  lint:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: sc-setup
      uses: soundcloud/sc-github-actions/sc-setup@master
      with:
        sc-tools: 'true'
    - name: make lint
      run: make lint
  unit-test:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: sc-setup
      uses: soundcloud/sc-github-actions/sc-setup@master
      with:
        sc-tools: 'true'
    - name: make unit-test
      run: make unit-test
  publish:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: sc-setup
      uses: soundcloud/sc-github-actions/sc-setup@master
      with:
        sc-tools: 'true'
    - name: make package publish
      run: make package publish
  check-prometheus:
    runs-on:
    - self-hosted
    - i-build-prod
    steps:
    - name: sc-setup
      uses: soundcloud/sc-github-actions/sc-setup@master
      with:
        sc-tools: 'true'
    - name: make check-prometheus
      run: make check-prometheus
